---
apiVersion: v1
kind: Service
metadata:
  name: traefik-mesh-injector-webhook
  labels:
    app: maesh
    component: injector
    chart: {{ include "traefikMesh.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: maesh
    component: injector
    release: {{ .Release.Name | quote }}
